const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/assets/images/products/p1.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/assets/images/products/p2.png",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/assets/images/products/p3.png",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/assets/images/products/p4.png",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 3.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/assets/images/products/p5.png",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/assets/images/products/p6.png",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 2.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/assets/images/products/p6.png",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 2,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "8",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/assets/images/products/p6.png",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 1.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "9",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/assets/images/products/p6.png",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 1,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "10",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/assets/images/products/p6.png",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 0,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};

export default data;
